title: "Dan Manole"
author: "Dan Manole"
description: "Production Cloud Infrastructure"
url: "https://itsdanmanole.com"
baseurl: ""

# _config.yml
style: auto # options: light, dark, auto
listen_for_clients_preferred_style: true
show_style_switcher: true

navigation:
  - title: "Archive"
    url: "/archive.html"

plugins:
  - jekyll-feed

permalink: /:year/:month/:title.html

# Simple Jekyll setup - original theme approach
markdown: kramdown
highlighter: rouge
